---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: data-catalogue
  name: data-catalogue
spec:
  replicas: 1
  selector:
    name: data-catalogue
    version: v0
  template:
    metadata:
      labels:
        name: data-catalogue
        version: v0
    spec:
      containers:
        -
          env:
            -
              name: DATABASE_URL
              value: "postgresql://ckan:ckan@db/ckan"
            -
              name: SOLR_URL
              value: "http://solr:8983/"
          image: "quay.io/ukhomeofficedigital/data-catalogue:"
          imagePullPolicy: Always
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 80
#            initialDelaySeconds: 60
#            timeoutSeconds: 60
          name: data-catalogue
          ports:
            -
              containerPort: 80
              name: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 80
#            initialDelaySeconds: 1
#            timeoutSeconds: 60
          resources:
           limits:
            cpu: 400m
            memory: 2048M
      restartPolicy: Always
